/**
 * Node Info - TypeScript equivalent of Blender node types
 * Based on infinigen/core/nodes/node_info.py
 * 
 * This enum maps to Three.js node types and shader node equivalents
 */

export enum NodeTypes {
  // Mix
  Mix = 'MixNode',

  // Attribute
  Attribute = 'AttributeNode',
  CaptureAttribute = 'CaptureAttributeNode',
  AttributeStatistic = 'AttributeStatisticNode',
  TransferAttribute = 'TransferAttributeNode',
  DomainSize = 'DomainSizeNode',
  StoreNamedAttribute = 'StoreNamedAttributeNode',
  NamedAttribute = 'NamedAttributeNode',
  RemoveAttribute = 'RemoveAttributeNode',
  SampleIndex = 'SampleIndexNode',
  SampleNearest = 'SampleNearestNode',
  SampleNearestSurface = 'SampleNearestSurfaceNode',

  // Color
  ColorRamp = 'ColorRampNode',
  MixRGB = 'MixRGBNode',
  RGBCurve = 'RGBCurveNode',
  BrightContrast = 'BrightContrastNode',
  Exposure = 'ExposureNode',
  CombineHSV = 'CombineHSVNode',
  SeparateRGB = 'SeparateRGBNode',
  SeparateColor = 'SeparateColorNode',
  CombineRGB = 'CombineRGBNode',
  CombineColor = 'CombineColorNode',

  // Curve
  CurveToMesh = 'CurveToMeshNode',
  CurveToPoints = 'CurveToPointsNode',
  MeshToCurve = 'MeshToCurveNode',
  SampleCurve = 'SampleCurveNode',
  SetCurveRadius = 'SetCurveRadiusNode',
  SetCurveTilt = 'SetCurveTiltNode',
  CurveLength = 'CurveLengthNode',
  CurveSplineType = 'CurveSplineTypeNode',
  SetHandlePositions = 'SetHandlePositionsNode',
  SplineParameter = 'SplineParameterNode',
  SubdivideCurve = 'SubdivideCurveNode',
  ResampleCurve = 'ResampleCurveNode',
  TrimCurve = 'TrimCurveNode',
  ReverseCurve = 'ReverseCurveNode',
  FillCurve = 'FillCurveNode',
  FilletCurve = 'FilletCurveNode',

  // Curve Primitives
  QuadraticBezier = 'QuadraticBezierNode',
  CurveCircle = 'CurveCircleNode',
  CurveLine = 'CurveLineNode',
  CurveBezierSegment = 'CurveBezierSegmentNode',

  // Geometry
  SetPosition = 'SetPositionNode',
  JoinGeometry = 'JoinGeometryNode',
  MergeByDistance = 'MergeByDistanceNode',
  SeparateGeometry = 'SeparateGeometryNode',
  BoundingBox = 'BoundingBoxNode',
  Transform = 'TransformNode',
  DeleteGeometry = 'DeleteGeometryNode',
  Proximity = 'ProximityNode',
  ConvexHull = 'ConvexHullNode',
  Raycast = 'RaycastNode',
  DuplicateElements = 'DuplicateElementsNode',
  Triangulate = 'TriangulateNode',

  // Input
  GroupInput = 'GroupInputNode',
  RGB = 'RGBNode',
  Boolean = 'BooleanNode',
  Value = 'ValueNode',
  RandomValue = 'RandomValueNode',
  CollectionInfo = 'CollectionInfoNode',
  ObjectInfo = 'ObjectInfoNode',
  Vector = 'VectorNode',
  InputID = 'InputIDNode',
  InputPosition = 'InputPositionNode',
  InputNormal = 'InputNormalNode',
  InputEdgeVertices = 'InputEdgeVerticesNode',
  InputEdgeAngle = 'InputEdgeAngleNode',
  InputColor = 'InputColorNode',
  InputMeshFaceArea = 'InputMeshFaceAreaNode',
  TextureCoord = 'TextureCoordNode',
  Index = 'IndexNode',
  AmbientOcclusion = 'AmbientOcclusionNode',
  Integer = 'IntegerNode',
  HueSaturationValue = 'HueSaturationNode',
  BlackBody = 'BlackBodyNode',

  // Instances
  RealizeInstances = 'RealizeInstancesNode',
  InstanceOnPoints = 'InstanceOnPointsNode',
  TranslateInstances = 'TranslateInstancesNode',
  RotateInstances = 'RotateInstancesNode',
  ScaleInstances = 'ScaleInstancesNode',

  // Material
  SetMaterial = 'SetMaterialNode',
  SetMaterialIndex = 'SetMaterialIndexNode',
  MaterialIndex = 'MaterialIndexNode',

  // Mesh
  SubdivideMesh = 'SubdivideMeshNode',
  MeshToVolume = 'MeshToVolumeNode',
  MeshToPoints = 'MeshToPointsNode',
  SetMeshNormals = 'SetMeshNormalsNode',
  DualMesh = 'DualMeshNode',
  ExtrudeMesh = 'ExtrudeMeshNode',
  ExtrudeMeshAlongNormal = 'ExtrudeMeshAlongNormalNode',
  OffsetMesh = 'OffsetMeshNode',
  FlipFaces = 'FlipFacesNode',
  FaceArea = 'FaceAreaNode',
  EdgeNeighbors = 'EdgeNeighborsNode',
  EdgesOfVertex = 'EdgesOfVertexNode',
  VerticesOfEdge = 'VerticesOfEdgeNode',
  VerticesOfFace = 'VerticesOfFaceNode',
  EdgesOfFace = 'EdgesOfFaceNode',
  FacesOfEdge = 'FacesOfEdgeNode',
  FacesOfVertex = 'FacesOfVertexNode',
  EdgeAngle = 'EdgeAngleNode',
  EdgeVertices = 'EdgeVerticesNode',
  FaceCorners = 'FaceCornersNode',
  NamedCorner = 'NamedCornerNode',
  CornerNormal = 'CornerNormalNode',
  CornerAngle = 'CornerAngleNode',
  CornerVertexIndex = 'CornerVertexIndexNode',
  CornerEdgeIndex = 'CornerEdgeIndexNode',
  CornerFaceIndex = 'CornerFaceIndexNode',
  UVMap = 'UVMapNode',
  UVWarp = 'UVWarpNode',
  SetUV = 'SetUVNode',
  // StoreNamedAttribute already defined in Attribute section
  // SetMaterial already defined in Material section

  // Point
  DistributePointsInVolume = 'DistributePointsInVolumeNode',
  DistributePointsOnFaces = 'DistributePointsOnFacesNode',
  PointsToCurves = 'PointsToCurvesNode',
  PointsToVolumes = 'PointsToVolumesNode',
  PointsToVertices = 'PointsToVerticesNode',
  Points = 'PointsNode',
  PointDomain = 'PointDomainNode',
  PointDomainSize = 'PointDomainSizeNode',
  PointIndex = 'PointIndexNode',
  PointPosition = 'PointPositionNode',
  PointVelocity = 'PointVelocityNode',
  PointRotation = 'PointRotationNode',
  PointScale = 'PointScaleNode',
  PointCount = 'PointCountNode',
  PointMaterialIndex = 'PointMaterialIndexNode',
  PointNamedAttribute = 'PointNamedAttributeNode',
  PointCaptureAttribute = 'PointCaptureAttributeNode',
  PointTransferAttribute = 'PointTransferAttributeNode',
  PointStoreNamedAttribute = 'PointStoreNamedAttributeNode',
  PointSampleIndex = 'PointSampleIndexNode',
  PointSampleNearest = 'PointSampleNearestNode',
  PointSampleNearestSurface = 'PointSampleNearestSurfaceNode',
  PointAttributeStatistic = 'PointAttributeStatisticNode',
  PointBlurAttribute = 'PointBlurAttributeNode',
  PointAccumulateAttribute = 'PointAccumulateAttributeNode',
  PointEvaluateonDomain = 'PointEvaluateonDomainNode',
  PointInterpolateCurves = 'PointInterpolateCurvesNode',
  PointSampleUVSurface = 'PointSampleUVSurfaceNode',
  PointIsViewport = 'PointIsViewportNode',
  PointImageInfo = 'PointImageInfoNode',
  PointCurveofPoint = 'PointCurveofPointNode',
  PointCurvesInfo = 'PointCurvesInfoNode',
  PointRadius = 'PointRadiusNode',
  PointEndpointSelection = 'PointEndpointSelectionNode',
  PointsofCurve = 'PointsofCurveNode',
  PointSplineResolution = 'PointSplineResolutionNode',
  PointOffsetPointinCurve = 'PointOffsetPointinCurveNode',
  PointSplineType = 'PointSplineTypeNode',
  PointSplineLength = 'PointSplineLengthNode',
  PointCurveTangent = 'PointCurveTangentNode',

  // Volume
  VolumeToMesh = 'VolumeToMeshNode',
  VolumeToPoints = 'VolumeToPointsNode',
  VolumeToCurve = 'VolumeToCurveNode',
  VolumeSample = 'VolumeSampleNode',
  VolumeValue = 'VolumeValueNode',
  VolumeDensity = 'VolumeDensityNode',
  VolumeEmission = 'VolumeEmissionNode',
  VolumeAbsorption = 'VolumeAbsorptionNode',
  VolumeScattering = 'VolumeScatteringNode',
  VolumePrincipled = 'VolumePrincipledNode',
  VolumeInfo = 'VolumeInfoNode',
  VolumeMaterialIndex = 'VolumeMaterialIndexNode',
  VolumeNamedAttribute = 'VolumeNamedAttributeNode',
  VolumeCaptureAttribute = 'VolumeCaptureAttributeNode',
  VolumeTransferAttribute = 'VolumeTransferAttributeNode',
  VolumeStoreNamedAttribute = 'VolumeStoreNamedAttributeNode',
  VolumeSampleIndex = 'VolumeSampleIndexNode',
  VolumeSampleNearest = 'VolumeSampleNearestNode',
  VolumeSampleNearestSurface = 'VolumeSampleNearestSurfaceNode',
  VolumeAttributeStatistic = 'VolumeAttributeStatisticNode',
  VolumeBlurAttribute = 'VolumeBlurAttributeNode',
  VolumeAccumulateAttribute = 'VolumeAccumulateAttributeNode',
  VolumeEvaluateonDomain = 'VolumeEvaluateonDomainNode',

  // Texture
  TextureBrick = 'TextureBrickNode',
  TextureChecker = 'TextureCheckerNode',
  TextureGradient = 'TextureGradientNode',
  TextureMagic = 'TextureMagicNode',
  TextureNoise = 'TextureNoiseNode',
  TextureVoronoi = 'TextureVoronoiNode',
  TextureWave = 'TextureWaveNode',
  TextureWhiteNoise = 'TextureWhiteNoiseNode',
  TextureMusgrave = 'TextureMusgraveNode',
  TextureGabor = 'TextureGaborNode',

  // Vector
  VectorMath = 'VectorMathNode',
  VectorRotate = 'VectorRotateNode',
  VectorTransform = 'VectorTransformNode',
  NormalMap = 'NormalMapNode',
  Normal = 'NormalNode',
  Tangent = 'TangentNode',
  TrueNormal = 'TrueNormalNode',
  Geometry = 'GeometryNode',
  HairInfo = 'HairInfoNode',
  ParticleInfo = 'ParticleInfoNode',
  Wireframe = 'WireframeNode',
  Wavelength = 'WavelengthNode',
  LightPath = 'LightPathNode',
  ShaderObjectInfo = 'ShaderObjectInfoNode',
  ParticleInfo_Shader = 'ParticleInfoShaderNode',
  LayerWeight = 'LayerWeightNode',
  UVMap_Shader = 'UVMapShaderNode',
  TextureCoord_Shader = 'TextureCoordShaderNode',
  Bevel = 'BevelNode',
  CameraData = 'CameraDataNode',
  NewGeometry = 'NewGeometryNode',
  JoinGeometry_Shader = 'JoinGeometryShaderNode',
  MeshInfo = 'MeshInfoNode',
  MaterialInfo = 'MaterialInfoNode',
  Value_Shader = 'ValueShaderNode',
  TexCoord = 'TexCoordNode',
  ObjectIndex = 'ObjectIndexNode',
  MaterialIndex_Shader = 'MaterialIndexShaderNode',
  RandomPerIsland = 'RandomPerIslandNode',
  IsCameraRay = 'IsCameraRayNode',
  IsShadowRay = 'IsShadowRayNode',
  IsDiffuseRay = 'IsDiffuseRayNode',
  IsGlossyRay = 'IsGlossyRayNode',
  IsTransmissionRay = 'IsTransmissionRayNode',
  IsVolumeRay = 'IsVolumeRayNode',
  IsReflectionRay = 'IsReflectionRayNode',
  IsRefractionRay = 'IsRefractionRayNode',
  RayDepth = 'RayDepthNode',
  RayLength = 'RayLengthNode',

  // Output
  GroupOutput = 'GroupOutputNode',
  MaterialOutput = 'MaterialOutputNode',
  Viewer = 'ViewerNode',
  Composite = 'CompositeNode',
  ViewLevel = 'ViewLevelNode',
  SplitViewer = 'SplitViewerNode',
  DepthOutput = 'DepthOutputNode',
  NormalOutput = 'NormalOutputNode',
  AOOutput = 'AOOutputNode',
  EmissionOutput = 'EmissionOutputNode',
  AlbedoOutput = 'AlbedoOutputNode',
  DiffuseOutput = 'DiffuseOutputNode',
  GlossyOutput = 'GlossyOutputNode',
  TransmissionOutput = 'TransmissionOutputNode',
  VolumeOutput = 'VolumeOutputNode',
  ShadowOutput = 'ShadowOutputNode',
  CryptomatteOutput = 'CryptomatteOutputNode',
  CryptomatteMatteOutput = 'CryptomatteMatteOutputNode',
  FileOutput = 'FileOutputNode',
  ImageOutput = 'ImageOutputNode',
  MovieOutput = 'MovieOutputNode',
  SoundOutput = 'SoundOutputNode',
  LevelOfDetail = 'LevelOfDetailNode',
  RenderLayer = 'RenderLayerNode',
  UVOutput = 'UVOutputNode',
  InstanceOutput = 'InstanceOutputNode',
  PointCloudOutput = 'PointCloudOutputNode',
  TextOutput = 'TextOutputNode',
  BoundingBoxOutput = 'BoundingBoxOutputNode',
  WireframeOutput = 'WireframeOutputNode',
  DebugOutput = 'DebugOutputNode',

  // Light
  PointLight = 'PointLightNode',
  SpotLight = 'SpotLightNode',
  SunLight = 'SunLightNode',
  AreaLight = 'AreaLightNode',
  LightFalloff = 'LightFalloffNode',
  LightAttenuation = 'LightAttenuationNode',

  // Boolean
  BooleanUnion = 'BooleanUnionNode',
  BooleanIntersect = 'BooleanIntersectNode',
  BooleanDifference = 'BooleanDifferenceNode',

  // Extended Vector
  CombineXYZ = 'CombineXYZNode',
  SeparateXYZ = 'SeparateXYZNode',
  Normalize = 'NormalizeNode',
  Mapping = 'MappingNode',
  AlignEulerToVector = 'AlignEulerToVectorNode',
  RotateEuler = 'RotateEulerNode',
  Bump = 'BumpNode',
  Displacement = 'DisplacementNode',
  Quaternion = 'QuaternionNode',
  MatrixTransform = 'MatrixTransformNode',
  DirectionToPoint = 'DirectionToPointNode',
  Reflect = 'ReflectNode',
  Refract = 'RefractNode',
  FaceForward = 'FaceForwardNode',
  Wrap = 'WrapNode',
  Snap = 'SnapNode',
  FloorCeil = 'FloorCeilNode',
  Modulo = 'ModuloNode',
  Fraction = 'FractionNode',
  Absolute = 'AbsoluteNode',
  MinMax = 'MinMaxNode',
  Trigonometry = 'TrigonometryNode',
  PowerLog = 'PowerLogNode',
  Sign = 'SignNode',
  Compare = 'CompareNode',
  SmoothMinMax = 'SmoothMinMaxNode',
  AngleBetween = 'AngleBetweenNode',
  Slerp = 'SlerpNode',
  PolarToCart = 'PolarToCartNode',
  CartToPolar = 'CartToPolarNode',
  HueSaturationValue = 'HueSaturationNode',

  // Subdivision
  SubdivisionSurface = 'SubdivisionSurfaceNode',

  // Attribute input aliases
  PositionInput = InputPosition,
  NormalInput = InputNormal,
  TangentInput = Tangent,
  UVMapInput = UVMap,
  ColorInput = InputColor,
  RadiusInput = 'RadiusInputNode',
  IdInput = InputID,
  IndexInput = Index,

  // Shader aliases
  BSDF_PRINCIPLED = 'PrincipledBSDFNode',
  PrincipledBSDF = 'PrincipledBSDFNode',
  NoiseTexture = TextureNoise,
  VoronoiTexture = TextureVoronoi,
  MusgraveTexture = TextureMusgrave,
  Invert = 'InvertNode',
  BooleanMath = 'BooleanMathNode',

  // Aliases - SCREAMING_SNAKE_CASE aliases for PascalCase members
  VECTOR_MATH = VectorMath,
  TEX_COORD = TexCoord,
  TEX_NOISE = TextureNoise,
  NORMAL_MAP = NormalMap,
  MAPPING = Mapping,
  LINE_OUTPUT = FileOutput,
  LOD_GROUP_OUTPUT = GroupOutput,
  LAYER_WEIGHT = LayerWeight,
  BUMP = Bump,
  COMPOSITE_OUTPUT = MovieOutput,
  AMBIENT_OCCLUSION_OUTPUT = AmbientOcclusion,
  COLOR_RAMP = ColorRamp,
  OUTPUT_NORMAL = NormalOutput,
  OUTPUT_COLOR = AlbedoOutput,
  OUTPUT_VECTOR = VectorMath,
  OUTPUT_MATERIAL = MaterialOutput,
  OUTPUT_VALUE = Value,

  // CamelCase aliases for referenced names
  CompositeOutput = MovieOutput,
  LODGroupOutput = GroupOutput,
  AmbientOcclusionOutput = AmbientOcclusion,
  LineOutput = FileOutput,
}

export default NodeTypes;
