/**
 * Spatial Relation Algebra
 *
 * Ports: infinigen/core/constraints/constraint_language/relations.py
 *
 * Defines a complete spatial relation algebra with:
 *  - Formal relation types (Touching, SupportedBy, CoPlanar, StableAgainst, etc.)
 *  - Implication lattice (which relations imply others)
 *  - Geometric constraint extraction (axis-aligned bounds for each relation)
 *  - Set algebra over relations: intersection, difference, negation
 *
 * This complements the existing Relation classes in ./relations.ts (which are
 * BoolExpression-based AST nodes for the constraint language) by providing
 * a pure algebraic layer for reasoning about spatial relations during
 * constraint solving — without needing a full AST evaluation context.
 *
 * The existing Relation hierarchy evaluates against a `Map<Variable, any>` state.
 * This module provides lightweight SpatialRelation objects that can:
 *  - Be checked for implication (does A imply B?)
 *  - Extract geometric constraints (bounds on position/orientation)
 *  - Be combined via intersection/difference (for domain pruning)
 *  - Be tested against a point+state (for feasibility checks)
 */

import * as THREE from 'three';

// ============================================================================
// Relation Type Enum
// ============================================================================

/**
 * Enumeration of all spatial relation types in the Infinigen constraint language.
 *
 * Each type corresponds to a spatial predicate that can hold between objects:
 * - TOUCHING: Objects are within a small margin of each other
 * - SUPPORTED_BY: Object A is vertically supported by object B
 * - COPLANAR: Objects lie on the same plane
 * - STABLE_AGAINST: Object A is stable when in contact with B
 * - ROOM_NEIGHBOUR: Rooms share a wall with a connector
 * - CUT_FROM: Object was generated by cutting from a parent
 * - SHARED_EDGE: Objects share a boundary edge
 * - TRAVERSE: A path exists between two rooms/regions
 */
export enum RelationType {
  TOUCHING = 'TOUCHING',
  SUPPORTED_BY = 'SUPPORTED_BY',
  COPLANAR = 'COPLANAR',
  STABLE_AGAINST = 'STABLE_AGAINST',
  ROOM_NEIGHBOUR = 'ROOM_NEIGHBOUR',
  CUT_FROM = 'CUT_FROM',
  SHARED_EDGE = 'SHARED_EDGE',
  TRAVERSE = 'TRAVERSE',
}

// ============================================================================
// Geometric Constraint Descriptor
// ============================================================================

/**
 * A geometric constraint extracted from a spatial relation.
 *
 * Describes an axis-aligned or directional bound on the position
 * of an object that must hold for the relation to be satisfied.
 */
export interface GeometricConstraint {
  /** Minimum value along the constraint axis */
  min: number;
  /** Maximum value along the constraint axis */
  max: number;
  /** Optional axis direction (defaults to the relation's natural axis) */
  axis?: THREE.Vector3;
}

// ============================================================================
// SpatialRelation Abstract Base
// ============================================================================

/**
 * Abstract base class for spatial relations in the relation algebra.
 *
 * Provides:
 *  - `implies`: Logical implication check (does this relation imply another?)
 *  - `satisfies`: Geometric test (does a point satisfy this relation?)
 *  - `intersects`: Set intersection (what's the overlap between two relations?)
 *  - `difference`: Set difference (this relation minus another)
 *  - `getConstraints`: Extract geometric bounds for constraint propagation
 *
 * The implication lattice (partial order):
 *   STABLE_AGAINST → SUPPORTED_BY → TOUCHING
 *   (If A is stable against B, then A is supported by B, then A is touching B)
 */
export abstract class SpatialRelation {
  /** The type of this relation */
  abstract readonly type: RelationType;

  /**
   * Whether this relation logically implies another relation.
   *
   * A implies B means: whenever A holds, B also holds.
   * For example, SUPPORTED_BY implies TOUCHING because
   * if an object is supported by another, it must be touching it.
   */
  abstract implies(other: SpatialRelation): boolean;

  /**
   * Whether a given point satisfies this spatial relation
   * given the current world state.
   *
   * @param point - The 3D position to test
   * @param state - Additional state (support surfaces, obstacles, etc.)
   */
  abstract satisfies(point: THREE.Vector3, state: any): boolean;

  /**
   * Compute the intersection of this relation with another.
   *
   * Returns a new relation that is satisfied only when BOTH
   * this relation AND the other are satisfied, or null if the
   * intersection is empty (the relations are mutually exclusive).
   */
  abstract intersects(other: SpatialRelation): SpatialRelation | null;

  /**
   * Compute the difference: this relation minus the other.
   *
   * Returns a relation satisfied when THIS holds but OTHER does not,
   * or null if this is a subset of other (difference is empty).
   */
  abstract difference(other: SpatialRelation): SpatialRelation | null;

  /**
   * Extract geometric constraints from this relation.
   *
   * Returns an array of axis-aligned bounds that any point satisfying
   * this relation must fall within. Used by the solver to prune
   * infeasible domain regions.
   */
  abstract getConstraints(): GeometricConstraint[];

  /**
   * Create a copy of this relation.
   */
  abstract clone(): SpatialRelation;
}

// ============================================================================
// Concrete Relation Implementations
// ============================================================================

/**
 * Touching relation: objects are within a small margin of each other.
 *
 * Implication: TOUCHING from above implies SUPPORTED_BY.
 * Geometric constraint: distance from target < margin.
 */
export class Touching extends SpatialRelation {
  readonly type = RelationType.TOUCHING;

  constructor(
    /** Maximum distance for "touching" */
    public readonly margin: number = 0.05,
    /** Whether the touching is from above (implies support) */
    public readonly fromAbove: boolean = false,
    /** Optional target position for distance computation */
    public readonly target?: THREE.Vector3
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    // TOUCHING from above implies SUPPORTED_BY
    if (this.fromAbove && other.type === RelationType.SUPPORTED_BY) {
      return true;
    }
    // Same type implies itself
    if (other.type === RelationType.TOUCHING && other instanceof Touching) {
      return this.margin <= other.margin;
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    if (!this.target) {
      // Without a target, check against any nearby surface in state
      if (state && state.surfaces) {
        for (const surface of state.surfaces) {
          const surfPos = surface instanceof THREE.Vector3
            ? surface
            : new THREE.Vector3(surface.x, surface.y, surface.z);
          if (point.distanceTo(surfPos) < this.margin) return true;
        }
      }
      return false;
    }
    return point.distanceTo(this.target) < this.margin;
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.TOUCHING && other instanceof Touching) {
      // Intersection is touching with the smaller margin
      const newMargin = Math.min(this.margin, other.margin);
      if (newMargin <= 0) return null;
      return new Touching(newMargin, this.fromAbove && other.fromAbove, this.target);
    }
    // Touching and SupportedBy can intersect if touching from above
    if (other.type === RelationType.SUPPORTED_BY && this.fromAbove) {
      return other; // SupportedBy is more specific
    }
    return null;
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.TOUCHING && other instanceof Touching) {
      if (other.margin >= this.margin) return null; // other subsumes this
      // This minus other = ring between other.margin and this.margin
      return new Touching(this.margin, this.fromAbove, this.target);
    }
    return this.clone();
  }

  getConstraints(): GeometricConstraint[] {
    return [{ min: 0, max: this.margin }];
  }

  clone(): Touching {
    return new Touching(this.margin, this.fromAbove, this.target?.clone());
  }
}

/**
 * SupportedBy relation: object A is vertically supported by object B.
 *
 * This means A's bottom is close to B's top, and they overlap in XZ.
 *
 * Implication: SUPPORTED_BY implies STABLE_AGAINST (with same margin).
 * Geometric constraint: vertical distance from support surface < margin.
 */
export class SupportedBy extends SpatialRelation {
  readonly type = RelationType.SUPPORTED_BY;

  /** Up direction (default Y-up) */
  private static readonly UP = new THREE.Vector3(0, 1, 0);

  constructor(
    /** Maximum vertical gap between supporter top and supported bottom */
    public readonly margin: number = 0.1,
    /** Whether to check vertical support (z-axis in Blender, y-axis in Three.js) */
    public readonly checkZ: boolean = true,
    /** Optional support surface position */
    public readonly supportPoint?: THREE.Vector3,
    /** Optional support surface height (top of supporter) */
    public readonly supportHeight?: number
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    // SUPPORTED_BY implies STABLE_AGAINST
    if (other.type === RelationType.STABLE_AGAINST) {
      return true;
    }
    // SUPPORTED_BY implies TOUCHING (with appropriate margin)
    if (other.type === RelationType.TOUCHING && other instanceof Touching) {
      return this.margin <= other.margin;
    }
    // Same type
    if (other.type === RelationType.SUPPORTED_BY && other instanceof SupportedBy) {
      return this.margin <= other.margin;
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    // Check if point is above a support surface
    if (this.supportPoint && this.supportHeight !== undefined) {
      const verticalDist = point.y - this.supportHeight;
      if (verticalDist < 0 || verticalDist > this.margin) return false;
      // Check XZ overlap (simplified: distance in XZ plane)
      const dxz = Math.sqrt(
        (point.x - this.supportPoint.x) ** 2 +
        (point.z - this.supportPoint.z) ** 2
      );
      return dxz < 2.0; // Reasonable XZ overlap threshold
    }

    // Fallback: check against state surfaces
    if (state && state.supportSurfaces) {
      for (const surface of state.supportSurfaces) {
        const surfHeight = surface.height ?? surface.y ?? 0;
        const surfPos = surface.position
          ? new THREE.Vector3(surface.position.x, surface.position.y, surface.position.z)
          : null;
        const verticalDist = point.y - surfHeight;
        if (verticalDist >= 0 && verticalDist <= this.margin) {
          if (!surfPos) return true;
          const dxz = Math.sqrt(
            (point.x - surfPos.x) ** 2 + (point.z - surfPos.z) ** 2
          );
          if (dxz < 2.0) return true;
        }
      }
    }
    return false;
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.SUPPORTED_BY && other instanceof SupportedBy) {
      const newMargin = Math.min(this.margin, other.margin);
      if (newMargin <= 0) return null;
      return new SupportedBy(newMargin, this.checkZ || other.checkZ, this.supportPoint, this.supportHeight);
    }
    if (other.type === RelationType.STABLE_AGAINST) {
      return this; // SupportedBy is more specific
    }
    if (other.type === RelationType.TOUCHING) {
      return this; // SupportedBy is more specific than Touching
    }
    return null;
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.SUPPORTED_BY && other instanceof SupportedBy) {
      if (other.margin >= this.margin) return null;
      return new SupportedBy(this.margin, this.checkZ, this.supportPoint, this.supportHeight);
    }
    return this.clone();
  }

  getConstraints(): GeometricConstraint[] {
    return [{
      min: 0,
      max: this.margin,
      axis: SupportedBy.UP.clone(),
    }];
  }

  clone(): SupportedBy {
    return new SupportedBy(this.margin, this.checkZ, this.supportPoint?.clone(), this.supportHeight);
  }
}

/**
 * CoPlanar relation: objects lie on the same plane.
 *
 * A point satisfies this if its distance to the reference plane
 * is less than the margin.
 */
export class CoPlanar extends SpatialRelation {
  readonly type = RelationType.COPLANAR;

  constructor(
    /** Maximum deviation from the plane */
    public readonly margin: number = 0.05,
    /** Whether to reverse the plane normal */
    public readonly revNormal: boolean = false,
    /** Plane normal (default: Y-up for horizontal coplanarity) */
    public readonly normal: THREE.Vector3 = new THREE.Vector3(0, 1, 0),
    /** Point on the reference plane */
    public readonly planePoint?: THREE.Vector3
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    if (other.type === RelationType.COPLANAR && other instanceof CoPlanar) {
      // More restrictive margin implies less restrictive
      return this.margin <= other.margin;
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    if (!this.planePoint) {
      // Without a plane reference, check Y-coplanarity with state objects
      if (state && state.referenceY !== undefined) {
        return Math.abs(point.y - state.referenceY) < this.margin;
      }
      return false;
    }
    // Signed distance from point to plane
    const normalDir = this.revNormal ? this.normal.clone().negate() : this.normal;
    const dist = point.clone().sub(this.planePoint).dot(normalDir);
    return Math.abs(dist) < this.margin;
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.COPLANAR && other instanceof CoPlanar) {
      // Two coplanar constraints intersect if their normals are similar
      const dotProduct = this.normal.dot(other.normal);
      if (Math.abs(dotProduct) > 0.99) { // Nearly parallel normals
        const newMargin = Math.min(this.margin, other.margin);
        return new CoPlanar(newMargin, this.revNormal, this.normal.clone(), this.planePoint);
      }
      // Non-parallel planes intersect in a line — represented as a tighter coplanar
      return new CoPlanar(Math.min(this.margin, other.margin), this.revNormal, this.normal.clone());
    }
    return null;
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.COPLANAR && other instanceof CoPlanar) {
      if (other.margin >= this.margin) return null;
      return new CoPlanar(this.margin, this.revNormal, this.normal.clone(), this.planePoint);
    }
    return this.clone();
  }

  getConstraints(): GeometricConstraint[] {
    // Plane equation constraint: distance to plane in [−margin, +margin]
    const normalDir = this.revNormal ? this.normal.clone().negate() : this.normal;
    return [{
      min: -this.margin,
      max: this.margin,
      axis: normalDir,
    }];
  }

  clone(): CoPlanar {
    return new CoPlanar(this.margin, this.revNormal, this.normal.clone(), this.planePoint?.clone());
  }
}

/**
 * StableAgainst relation: object A is stable when in contact with B.
 *
 * This is stronger than SupportedBy — it requires not just vertical
 * support but also sufficient contact area and friction to prevent
 * sliding or tipping.
 *
 * Implication: STABLE_AGAINST implies SUPPORTED_BY.
 */
export class StableAgainst extends SpatialRelation {
  readonly type = RelationType.STABLE_AGAINST;

  constructor(
    /** Maximum gap between objects */
    public readonly margin: number = 0.05,
    /** Whether to check vertical support */
    public readonly checkZ: boolean = true,
    /** Whether to reverse the contact normal */
    public readonly revNormal: boolean = false,
    /** Contact normal direction */
    public readonly contactNormal: THREE.Vector3 = new THREE.Vector3(0, 1, 0),
    /** Contact point on the support surface */
    public readonly contactPoint?: THREE.Vector3
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    // STABLE_AGAINST implies SUPPORTED_BY
    if (other.type === RelationType.SUPPORTED_BY) {
      return true;
    }
    // STABLE_AGAINST implies TOUCHING
    if (other.type === RelationType.TOUCHING && other instanceof Touching) {
      return this.margin <= other.margin;
    }
    if (other.type === RelationType.STABLE_AGAINST && other instanceof StableAgainst) {
      return this.margin <= other.margin;
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    if (!this.contactPoint) {
      // Check against state
      if (state && state.stableSurfaces) {
        for (const surface of state.stableSurfaces) {
          const surfPos = surface instanceof THREE.Vector3
            ? surface
            : new THREE.Vector3(surface.x, surface.y, surface.z);
          const dist = point.distanceTo(surfPos);
          if (dist < this.margin) {
            // Check stability: contact normal should be roughly up
            const normalDir = this.revNormal
              ? this.contactNormal.clone().negate()
              : this.contactNormal;
            if (this.checkZ && normalDir.y < 0.5) continue;
            return true;
          }
        }
      }
      return false;
    }

    // Check distance to contact point
    const dist = point.distanceTo(this.contactPoint);
    if (dist > this.margin) return false;

    // Check contact normal direction
    const normalDir = this.revNormal
      ? this.contactNormal.clone().negate()
      : this.contactNormal;
    if (this.checkZ && normalDir.y < 0.5) return false;

    return true;
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.STABLE_AGAINST && other instanceof StableAgainst) {
      const newMargin = Math.min(this.margin, other.margin);
      return new StableAgainst(newMargin, this.checkZ && other.checkZ, this.revNormal, this.contactNormal.clone());
    }
    if (other.type === RelationType.SUPPORTED_BY) {
      // Stable + Supported → more restrictive Stable
      return new StableAgainst(
        Math.min(this.margin, other instanceof SupportedBy ? other.margin : this.margin),
        this.checkZ,
        this.revNormal,
        this.contactNormal.clone()
      );
    }
    return null;
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.STABLE_AGAINST && other instanceof StableAgainst) {
      if (other.margin >= this.margin) return null;
      return new StableAgainst(this.margin, this.checkZ, this.revNormal, this.contactNormal.clone());
    }
    return this.clone();
  }

  getConstraints(): GeometricConstraint[] {
    const normalDir = this.revNormal
      ? this.contactNormal.clone().negate()
      : this.contactNormal;
    return [{
      min: 0,
      max: this.margin,
      axis: normalDir,
    }];
  }

  clone(): StableAgainst {
    return new StableAgainst(this.margin, this.checkZ, this.revNormal, this.contactNormal.clone(), this.contactPoint?.clone());
  }
}

/**
 * RoomNeighbour relation: two rooms share a wall with a connector.
 *
 * The connector can be a door, an open passage, or a wall segment.
 */
export class RoomNeighbour extends SpatialRelation {
  readonly type = RelationType.ROOM_NEIGHBOUR;

  constructor(
    /** Types of connectors allowed between the rooms */
    public readonly connectorTypes: ('door' | 'open' | 'wall')[] = ['door', 'open'],
    /** ID of the first room */
    public readonly roomA?: string,
    /** ID of the second room */
    public readonly roomB?: string
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    if (other.type === RelationType.ROOM_NEIGHBOUR && other instanceof RoomNeighbour) {
      // If our connectors are a subset of other's, we imply other
      return other.connectorTypes.every(ct => this.connectorTypes.includes(ct));
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    // Check if point is in a room that neighbours another room
    if (!state || !state.roomGraph) return false;

    const roomGraph = state.roomGraph;
    if (typeof roomGraph.areNeighbours === 'function') {
      return roomGraph.areNeighbours(this.roomA, this.roomB, this.connectorTypes);
    }

    // Fallback: check room adjacency by position
    if (state.rooms) {
      for (const room of state.rooms) {
        const roomPos = room.position
          ? new THREE.Vector3(room.position.x, room.position.y, room.position.z)
          : null;
        if (roomPos && point.distanceTo(roomPos) < 5.0) {
          return true;
        }
      }
    }
    return false;
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.ROOM_NEIGHBOUR && other instanceof RoomNeighbour) {
      const sharedConnectors = this.connectorTypes.filter(ct => other.connectorTypes.includes(ct));
      if (sharedConnectors.length === 0) return null;
      return new RoomNeighbour(sharedConnectors as ('door' | 'open' | 'wall')[], this.roomA, this.roomB);
    }
    return null;
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.ROOM_NEIGHBOUR && other instanceof RoomNeighbour) {
      const remaining = this.connectorTypes.filter(ct => !other.connectorTypes.includes(ct));
      if (remaining.length === 0) return null;
      return new RoomNeighbour(remaining as ('door' | 'open' | 'wall')[], this.roomA, this.roomB);
    }
    return this.clone();
  }

  getConstraints(): GeometricConstraint[] {
    // Room neighbour constraints depend on room geometry
    // Provide a loose bound based on typical room sizes
    return [{ min: 0, max: 10 }]; // Within 10m of room boundary
  }

  clone(): RoomNeighbour {
    return new RoomNeighbour([...this.connectorTypes], this.roomA, this.roomB);
  }
}

/**
 * CutFrom relation: object was generated by cutting from a parent shape.
 *
 * Used in CSG (Constructive Solid Geometry) operations.
 */
export class CutFrom extends SpatialRelation {
  readonly type = RelationType.CUT_FROM;

  constructor(
    /** ID of the parent shape */
    public readonly parentId?: string
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    if (other.type === RelationType.CUT_FROM && other instanceof CutFrom) {
      return this.parentId === other.parentId;
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    // A point satisfies CutFrom if it's inside the parent shape
    if (!state || !state.parentBounds) return false;
    const bounds = state.parentBounds;
    return (
      point.x >= bounds.minX && point.x <= bounds.maxX &&
      point.y >= bounds.minY && point.y <= bounds.maxY &&
      point.z >= bounds.minZ && point.z <= bounds.maxZ
    );
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.CUT_FROM && other instanceof CutFrom) {
      if (this.parentId === other.parentId) return this.clone();
      return null; // Different parents = no intersection
    }
    return null;
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.CUT_FROM && other instanceof CutFrom) {
      if (this.parentId === other.parentId) return null;
    }
    return this.clone();
  }

  getConstraints(): GeometricConstraint[] {
    return [{ min: -Infinity, max: Infinity }];
  }

  clone(): CutFrom {
    return new CutFrom(this.parentId);
  }
}

/**
 * SharedEdge relation: two objects share a boundary edge.
 *
 * Common in floor plans and room layouts where walls/rooms
 * share edges.
 */
export class SharedEdge extends SpatialRelation {
  readonly type = RelationType.SHARED_EDGE;

  constructor(
    /** Tolerance for edge overlap */
    public readonly margin: number = 0.01
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    if (other.type === RelationType.TOUCHING && other instanceof Touching) {
      return this.margin <= other.margin;
    }
    if (other.type === RelationType.SHARED_EDGE && other instanceof SharedEdge) {
      return this.margin <= other.margin;
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    if (!state || !state.edges) return false;
    for (const edge of state.edges) {
      const start = new THREE.Vector3(edge.start.x, edge.start.y, edge.start.z);
      const end = new THREE.Vector3(edge.end.x, edge.end.y, edge.end.z);
      // Distance from point to line segment
      const dist = this.pointToSegmentDist(point, start, end);
      if (dist < this.margin) return true;
    }
    return false;
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.SHARED_EDGE && other instanceof SharedEdge) {
      return new SharedEdge(Math.min(this.margin, other.margin));
    }
    return null;
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.SHARED_EDGE && other instanceof SharedEdge) {
      if (other.margin >= this.margin) return null;
      return new SharedEdge(this.margin);
    }
    return this.clone();
  }

  getConstraints(): GeometricConstraint[] {
    return [{ min: 0, max: this.margin }];
  }

  clone(): SharedEdge {
    return new SharedEdge(this.margin);
  }

  /** Compute distance from a point to a line segment */
  private pointToSegmentDist(p: THREE.Vector3, a: THREE.Vector3, b: THREE.Vector3): number {
    const ab = b.clone().sub(a);
    const ap = p.clone().sub(a);
    const t = Math.max(0, Math.min(1, ap.dot(ab) / ab.lengthSq()));
    const closest = a.clone().add(ab.multiplyScalar(t));
    return p.distanceTo(closest);
  }
}

/**
 * Traverse relation: a path exists between two rooms/regions.
 *
 * Used for navigation and accessibility constraints.
 */
export class Traverse extends SpatialRelation {
  readonly type = RelationType.TRAVERSE;

  constructor(
    /** Maximum path length (Infinity = any path) */
    public readonly maxPathLength: number = Infinity,
    /** Required connector types along the path */
    public readonly requireConnectorTypes: ('door' | 'open' | 'wall')[] = []
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    if (other.type === RelationType.ROOM_NEIGHBOUR) {
      // If we can traverse with path length ~0, we're neighbours
      return this.maxPathLength <= 0.1;
    }
    if (other.type === RelationType.TRAVERSE && other instanceof Traverse) {
      return this.maxPathLength <= other.maxPathLength;
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    if (!state || !state.navigationGraph) return false;
    // Check if the point is reachable via the navigation graph
    if (typeof state.navigationGraph.isReachable === 'function') {
      return state.navigationGraph.isReachable(point, this.maxPathLength);
    }
    return true;
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.TRAVERSE && other instanceof Traverse) {
      return new Traverse(
        Math.min(this.maxPathLength, other.maxPathLength),
        [...new Set([...this.requireConnectorTypes, ...other.requireConnectorTypes])]
      );
    }
    return null;
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    if (other.type === RelationType.TRAVERSE && other instanceof Traverse) {
      if (other.maxPathLength >= this.maxPathLength) return null;
      return new Traverse(this.maxPathLength, this.requireConnectorTypes);
    }
    return this.clone();
  }

  getConstraints(): GeometricConstraint[] {
    return [{ min: 0, max: this.maxPathLength }];
  }

  clone(): Traverse {
    return new Traverse(this.maxPathLength, [...this.requireConnectorTypes]);
  }
}

// ============================================================================
// NegatedRelation
// ============================================================================

/**
 * Negated relation: NOT(inner).
 *
 * Satisfies when the inner relation does NOT satisfy.
 * Implements De Morgan's laws for intersection/difference.
 */
export class NegatedRelation extends SpatialRelation {
  readonly type: RelationType = RelationType.TOUCHING; // Placeholder; negation is meta

  constructor(
    /** The inner relation being negated */
    public readonly inner: SpatialRelation
  ) {
    super();
  }

  implies(other: SpatialRelation): boolean {
    // NOT(A) implies NOT(B) if B implies A (contrapositive)
    // i.e., if B => A, then NOT(A) => NOT(B)
    if (other instanceof NegatedRelation) {
      return other.inner.implies(this.inner);
    }
    return false;
  }

  satisfies(point: THREE.Vector3, state: any): boolean {
    return !this.inner.satisfies(point, state);
  }

  intersects(other: SpatialRelation): SpatialRelation | null {
    // De Morgan: NOT(A) ∩ NOT(B) = NOT(A ∪ B)
    // For now, we return a simplified result
    if (other instanceof NegatedRelation) {
      // NOT(A) ∩ NOT(B) = NOT(A OR B)
      // Represented as NegatedRelation — we'd need an OrRelation for full fidelity
      // For simplicity, return the more restrictive negation
      return new NegatedRelation(other.inner);
    }
    // NOT(A) ∩ B = B \ A
    return other.difference(this.inner);
  }

  difference(other: SpatialRelation): SpatialRelation | null {
    // NOT(A) \ NOT(B) = NOT(A) ∩ B = B \ A
    if (other instanceof NegatedRelation) {
      return this.inner.difference(other.inner);
    }
    // NOT(A) \ B = NOT(A ∪ B)
    return new NegatedRelation(other);
  }

  getConstraints(): GeometricConstraint[] {
    // Negated constraints are open intervals — hard to represent as bounds
    // Return unbounded constraints (the solver must handle negation separately)
    return [{ min: -Infinity, max: Infinity }];
  }

  clone(): NegatedRelation {
    return new NegatedRelation(this.inner.clone());
  }
}

// ============================================================================
// Factory Function
// ============================================================================

/**
 * Factory function to create a SpatialRelation from a RelationType and parameters.
 *
 * @param type - The relation type to create
 * @param params - Optional parameters specific to each relation type
 * @returns A new SpatialRelation instance
 *
 * @example
 * ```ts
 * const touching = createRelation(RelationType.TOUCHING, { margin: 0.1 });
 * const supported = createRelation(RelationType.SUPPORTED_BY, { margin: 0.05, checkZ: true });
 * const coplanar = createRelation(RelationType.COPLANAR, { margin: 0.02, revNormal: false });
 * ```
 */
export function createRelation(
  type: RelationType,
  params?: Record<string, any>
): SpatialRelation {
  const p = params ?? {};

  switch (type) {
    case RelationType.TOUCHING:
      return new Touching(
        p.margin ?? 0.05,
        p.fromAbove ?? false,
        p.target ? new THREE.Vector3(p.target.x, p.target.y, p.target.z) : undefined
      );

    case RelationType.SUPPORTED_BY:
      return new SupportedBy(
        p.margin ?? 0.1,
        p.checkZ ?? true,
        p.supportPoint ? new THREE.Vector3(p.supportPoint.x, p.supportPoint.y, p.supportPoint.z) : undefined,
        p.supportHeight
      );

    case RelationType.COPLANAR:
      return new CoPlanar(
        p.margin ?? 0.05,
        p.revNormal ?? false,
        p.normal ? new THREE.Vector3(p.normal.x, p.normal.y, p.normal.z) : undefined,
        p.planePoint ? new THREE.Vector3(p.planePoint.x, p.planePoint.y, p.planePoint.z) : undefined
      );

    case RelationType.STABLE_AGAINST:
      return new StableAgainst(
        p.margin ?? 0.05,
        p.checkZ ?? true,
        p.revNormal ?? false,
        p.contactNormal ? new THREE.Vector3(p.contactNormal.x, p.contactNormal.y, p.contactNormal.z) : undefined,
        p.contactPoint ? new THREE.Vector3(p.contactPoint.x, p.contactPoint.y, p.contactPoint.z) : undefined
      );

    case RelationType.ROOM_NEIGHBOUR:
      return new RoomNeighbour(
        p.connectorTypes ?? ['door', 'open'],
        p.roomA,
        p.roomB
      );

    case RelationType.CUT_FROM:
      return new CutFrom(p.parentId);

    case RelationType.SHARED_EDGE:
      return new SharedEdge(p.margin ?? 0.01);

    case RelationType.TRAVERSE:
      return new Traverse(
        p.maxPathLength ?? Infinity,
        p.requireConnectorTypes ?? []
      );

    default:
      throw new Error(`Unknown relation type: ${type}`);
  }
}
